drone:
  extraSecretNamesForEnvFrom:
    - droneci-secrets

  env:
    DRONE_SERVER_HOST: drone.evilgarfield.com
    DRONE_SERVER_PROTO: https
    DRONE_USER_CREATE: username:zhala,admin:true

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host drone.evilgarfield.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: drone-tls-certificate
        hosts:
          - *host

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    size: 8Gi
    storageClass: longhorn