graphite-exporter:
  serviceMonitor:
    enabled: true
  service:
    graphite:
      type: LoadBalancer
      port: 2003
      annotations:
        metallb.universe.tf/allow-shared-ip: graphite-exporter