kube-prometheus-stack:
  grafana:
    adminPassword: null
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - &host grafana.zanelab.com
      tls:
        - secretName: grafana-general-tls
          hosts:
            - *host
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
    persistence:
      type: pvc
      enabled: true
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      size: 5Gi

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      enableRemoteWriteReceiver: true
      additionalScrapeConfigs:
        - job_name: "hass"
          metrics_path: /api/prometheus
          scrape_interval: 60s
          authorization:
            credentials: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYzQ0NWMzMzhjNTY0NTA5YTZiOTQ0NGQ5ODJhYzhjZCIsImlhdCI6MTY2MjUxMjIwMCwiZXhwIjoxOTc3ODcyMjAwfQ.-3r22atsl1_FD_fyfbvEBwCFpWakouNMXGuVmRnJJk0"
          scheme: https
          static_configs:
            - targets: ['ha.zanelab.com']
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: freenas-nfs-csi
            accessModes: 
              - ReadWriteMany
            resources:
              requests:
                storage: 50Gi
    additionalPrometheusRulesMap:
      alert-test:
        groups:
        - name: "kubernetes.rules"
          rules:
          - alert: KubernetesNodeReady
            expr: kube_node_status_condition{condition="Ready",status="true"} == 0
            for: 10m
            labels:
              severity: critical
            annotations:
              summary: Kubernetes Node ready (instance {{ $labels.instance }})
              description: "Node {{ $labels.node }} has been unready for a long time\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
