democratic-csi:
  csiDriver:
    # should be globally unique for a given cluster
    name: "org.democratic-csi.nfs"

  controller:
    driver:
      image: docker.io/democraticcsi/democratic-csi:v1.8.4
  node:
    driver:
     image: docker.io/democraticcsi/democratic-csi:v1.8.4

  storageClasses:
  - name: freenas-nfs-csi
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs

    mountOptions:
    - noatime
    - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    existingConfigSecret: truenas-config
    config:
      driver: freenas-nfs
      instance_id:
      httpConnection:
        protocol: http
        host: 10.0.1.5
        port: 80
        username: root
        password: ""
        allowInsecure: true
      sshConnection:
        host: 10.0.1.5
        port: 22
        username: root
        password: ""
      zfs:
        datasetParentName: vdev1/k8s/nfs/vols
        detachedSnapshotsDatasetParentName: vdev1/k8s/nfs/snaps
        datasetEnableQuotas: true
        datasetEnableReservation: false
        datasetPermissionsMode: "0777"
        datasetPermissionsUser: root
        datasetPermissionsGroup: wheel
      nfs:
        shareHost: 10.0.1.5
        shareAlldirs: false
        shareAllowedHosts: []
        shareAllowedNetworks: []
        shareMaprootUser: root
        shareMaprootGroup: wheel
        shareMapallUser: ""
        shareMapallGroup: ""