kind: pipeline
type: kubernetes
name: push

steps:
- name: helm-lint
  image: alpine/helm
  commands: 
  - find . -name Chart.yaml -print | sed s/Chart.yaml//g | awk -F"/" '{print NF $0}' | sort -nr | sed 's/^.//' | xargs -n1 helm dep build
  # - find . -name Chart.yaml -print | sed s/Chart.yaml//g | awk -F"/" '{print NF $0}' | sort -nr | sed 's/^.//' | xargs -n1 helm lint