cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: 2024.8.2
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab-prod
    ingress:
      # It is safe to put a wildcard here
      # Please see https://homelab.evilgarfield.com/reference/faq.html#is-it-safe-to-use-wildcard-in-cloudflare-tunnel-ingress-config
      - hostname: '*.evilgarfield.com'
        service: https://ingress-nginx-controller.ingress-nginx
        originRequest:
          noTLSVerify: true
      - service: http_status:404

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
