drone:
  extraSecretNamesForEnvFrom:
    - droneci-secrets

  env:
    DRONE_SERVER_HOST: drone.zanelab.com
    DRONE_SERVER_PROTO: https

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host drone.zanelab.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: drone-tls-certificate
        hosts:
          - *host

drone-kube-runner:
  extraSecretNamesForEnvFrom:
    - droneci-secrets
  env:
    DRONE_SERVER_HOST: drone.zanelab.com
    DRONE_SERVER_PROTO: https
    DRONE_NAMESPACE_DEFAULT: droneci