drone:
  extraSecretNamesForEnvFrom:
    - droneci-secrets

  env:
    DRONE_SERVER_HOST: drone.zanelab.com
    DRONE_SERVER_PROTO: https

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host drone.zanelab.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secret-name: droneci-tls-certificate
        hosts:
          - *host