gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
    hosts:
      - host: &host git.zanelab.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.zanelab.com
      webhook:
        ALLOWED_HOST_LIST: "*.zanelab.com,*.slack.com"
  persistence:
    storageClass: longhorn
  postgresql:
    persistence:
      storageClass: longhorn
