apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: test-triggertemplate
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
    - name: gitrepositoryfullname
      description: repo full name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-run-
        namespace: $(tt.params.namespace)
      spec:
        serviceAccountName: tekton-triggers-sa
        pipelineRef:
          name: test-pipeline
        resources:
          - name: source-repo
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(tt.params.gitrevision)
              - name: url
                value: $(tt.params.gitrepositoryurl)
          - name: image-source
            resourceSpec:
              type: image
              params:
                - name: url
                  value: registry.zanelab.com/testrepo:$(tt.params.gitrevision) # docker-repo-location.com/repo:getting-started
        params:
          - name: git-sha
            value: $(tt.params.gitrevision)
          - name: repo-full-name
            value: $(tt.params.gitrepositoryfullname)
          - name: token-secret-name
            value: webhook-secret
          - name: token-secret-key
            value: token
          - name: target-url
            value: tekton.zanelab.com
          - name: description
            value: test-status
          - name: state
            value: pending
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: test-pipelinebinding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: tekton-pipelines
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: gitrepositoryfullname
      value: $(body.repository.full_name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
      - ref: test-pipelinebinding
      template:
        ref: test-triggertemplate