frigate:
  envFromSecrets:
    - frigate-rstp-credentials
  config: |
    mqtt:
      enabled: false
    detectors:
      detector_name:
        type: cpu
    cameras:
      back_garage:
        ffmpeg:
          inputs:
            - path: rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@20.0.1.4:554/cam/realmonitor?channel=1&subtype=0
              roles:
                - detect  
                - rtmp
                - record
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  persistence:
    data:
      enabled: true
      storageClass: freenas-nfs-csi
      accessMode: ReadWriteOnce
      size: 500Gi
  extraVolumeMounts:
  - name: data
    mountPath: /media
    subPath: frigate

  ingress:
    enabled: true

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
    - host: &host frigate.zanelab.com
      paths:
        - '/'

    tls:
      - secretName: frigate-tls-certificate
        hosts:
          - *host
