home-assistant:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host ha.zanelab.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ha-tls-certificate
          hosts:
            - *host
