esphome:
  image:
    tag: "2022.11"

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host esphome.zanelab.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: esphome-tls-certificate
          hosts:
            - *host
  env:
    DISABLE_HA_AUTHENTICATION: true

  persistence:
    pvc:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi
      mountPath: /config
      readOnly: false
      storageClass: longhorn